# Cloudflare configuration for Cities Collective
# This file should be placed in your project root

[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18"

# Security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
for = "/api/cities/*/images/*"
[headers.values]
Cache-Control = "public, max-age=3600"

# Don't cache API routes
[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

# Redirects
[[redirects]]
from = "/*"
to = "/index.html"
status = 200 